//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inf_sys_geogr_
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllForTests
    {
        public int id { get; set; }
        public string TestTopic { get; set; }
        public System.TimeSpan TestTime { get; set; }
        public int TestScores { get; set; }
        public string QuestAnswerTrueAnswer { get; set; }
    }
}
