//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inf_sys_geogr_
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllForTests
    {
        public int id { get; set; }
        public string topic { get; set; }
        public string questAndAnswerOptions { get; set; }
        public string trueAnswer { get; set; }
        public Nullable<int> priceThrows { get; set; }
        public Nullable<int> testTime { get; set; }
    }
}
