//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inf_sys_geogr_
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatistics
    {
        public int Nomer { get; set; }
        public string UserName { get; set; }
        public string TestName { get; set; }
        public string TrueAnswer { get; set; }
        public string SetBalls { get; set; }
        public string Way { get; set; }
        public int Assessment { get; set; }
        public string traveltime { get; set; }
    }
}
